### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by turbolent** [fclaude/libcds#12]
When trying to compile on Mac OS X 10.9.2 with clang (Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn):

```
  CXX    static/coders/huff.lo
static/coders/huff.cpp:173:25: error: reference to 'bitset' is ambiguous
                        if ((code >> d) & 1) bitset(stream,ptr);
                                             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/bitset:639:29: note: candidate found by name lookup is 'std::__1::bitset'
class _LIBCPP_TYPE_VIS_ONLY bitset
                            ^
../include/libcdsBasics.h:122:14: note: candidate found by name lookup is 'cds_utils::bitset'
        inline void bitset(uint * e, size_t p) {
                    ^
```

**Comment by RubenVerborgh** [comment]
c3002bef485ac00ed42e544c1aa2699b4d8c9311 fixes this issue.
